# Generated by Django 4.2.6 on 2023-10-24 00:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='company')),
                ('subtitle', models.TextField(max_length=1000)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('salary_start', models.IntegerField(blank=True, null=True)),
                ('salary_end', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(max_length=15000)),
                ('vacancy', models.IntegerField()),
                ('job_type', models.CharField(choices=[('FullTime', 'FullTime'), ('PartTime', 'ParTime'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=10)),
                ('experience', models.IntegerField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_company', to='job.company')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_category', to='job.category')),
            ],
        ),
    ]
