# Generated by Django 4.2.6 on 2023-10-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Company',
            new_name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_end',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
