# Generated by Django 4.2.6 on 2023-10-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_company_job_company_job_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
